#!/usr/bin/env bash
# Generated by //bazel:deploy.bzl. Publishes the built site to a git branch.
set -euo pipefail

dry_run=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) dry_run=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

site="$(cd "$(dirname "$0")" && pwd)/$(basename "$0").runfiles/_main/{{SITE}}"
[[ -d "$site" ]] || site="${RUNFILES_DIR:-$0.runfiles}/_main/{{SITE}}"
[[ -d "$site" ]] || { echo "built site not found at $site" >&2; exit 1; }
cd "${BUILD_WORKSPACE_DIRECTORY:?run me with bazel run}"

branch="{{BRANCH}}"
remote="{{REMOTE}}"
rev="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
work="$(mktemp -d)"
trap 'git worktree remove --force "$work" >/dev/null 2>&1 || true; rm -rf "$work"' EXIT

if git rev-parse --verify --quiet "refs/heads/$branch" >/dev/null; then
  git worktree add --quiet "$work" "$branch"
elif git ls-remote --exit-code --heads "$remote" "$branch" >/dev/null 2>&1; then
  git fetch --quiet "$remote" "$branch:$branch"
  git worktree add --quiet "$work" "$branch"
else
  git worktree add --quiet --detach "$work"
  git -C "$work" checkout --quiet --orphan "$branch"
fi

git -C "$work" rm -rqf --ignore-unmatch . >/dev/null
cp -RL "$site"/. "$work"/
chmod -R u+w "$work"
touch "$work/.nojekyll"
git -C "$work" add -A
if git -C "$work" diff --cached --quiet; then
  echo "site unchanged; nothing to deploy"
  exit 0
fi
git -C "$work" commit --quiet -m "{{MESSAGE}} ($rev)"
echo "committed $(git -C "$work" rev-parse --short HEAD) to $branch"

if (( dry_run )); then
  echo "dry run: not pushing (git push $remote $branch to publish)"
else
  git -C "$work" push "$remote" "$branch"
fi
